import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { useContractKit } from '@celo-tools/use-contractkit';
import { useEffect } from 'react';
import { useContract } from '@/hooks/useContract';
import Events from '@/components/Events';
import LandingPage from '@/components/LandingPage';
import { getMyEvents } from '@/hooks/blockchain';

export default function Home() {
  const contract = useContract();
  const { address } = useContractKit();

  useEffect(() => {
    const loadData = async () => {
      getMyEvents(contract, address);    };
    loadData();
  }, [contract, address]);

  return (
    <>
      <Head>
        <title>Yobooking</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <LandingPage />
      </div>
    </>
  );
}
